// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EventCreate = {
    title: string;
    description?: (string | null);
    location_name: string;
    event_datetime: string;
    latitude?: (string | null);
    longitude?: (string | null);
};

export type EventPublic = {
    id: string;
    title: string;
    description: (string | null);
    location_name: string;
    event_datetime: string;
    latitude: (string | null);
    longitude: (string | null);
    host_id: string;
};

export type EventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

export type EventUpdate = {
    title?: (string | null);
    description?: (string | null);
    location_name?: (string | null);
    event_datetime?: (string | null);
    latitude?: (string | null);
    longitude?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TagCreate = {
    name: string;
};

export type TagPublic = {
    id: string;
    name: string;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagUpdate = {
    name?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    first_name?: (string | null);
    last_name?: (string | null);
    gender?: (string | null);
    date_of_birth: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = (EventsPublic);

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadEventData = {
    eventId: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    eventId: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsDeleteEventData = {
    eventId: string;
};

export type EventsDeleteEventResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TagsReadTagsData = {
    limit?: number;
    skip?: number;
};

export type TagsReadTagsResponse = (TagsPublic);

export type TagsCreateTagData = {
    requestBody: TagCreate;
};

export type TagsCreateTagResponse = (TagPublic);

export type TagsReadTagData = {
    tagId: string;
};

export type TagsReadTagResponse = (TagPublic);

export type TagsUpdateTagData = {
    requestBody: TagUpdate;
    tagId: string;
};

export type TagsUpdateTagResponse = (TagPublic);

export type TagsDeleteTagData = {
    tagId: string;
};

export type TagsDeleteTagResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UserTagsListUserTagsData = {
    userId: string;
};

export type UserTagsListUserTagsResponse = (Array<TagPublic>);

export type UserTagsAssignTagData = {
    tagId: string;
    userId: string;
};

export type UserTagsAssignTagResponse = (void);

export type UserTagsUnassignTagData = {
    tagId: string;
    userId: string;
};

export type UserTagsUnassignTagResponse = (void);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);